import {
  HeroSlide,
  FeaturedBatch,
  OngoingBatch,
  LiveClass,
  Lecture,
  CourseItem,
  NavItem,
  HubItem,
  ChatbotConfig,
  DailyQuote,
} from "@/types/student-home.types";

export const STUDENT_NAV_ITEMS: NavItem[] = [
  { id: "home", label: "Home", href: "/student", iconName: "Home", isActive: true },
  { id: "my-learning", label: "My Learning", href: "/student/learning", iconName: "GraduationCap" },
  { id: "progress", label: "Progress", href: "/student/progress", iconName: "TrendingUp" },
  { id: "live-classes", label: "Live Classes", href: "/student/live", iconName: "PlaySquare" },
  { id: "tests", label: "Tests & Practice", href: "/student/tests", iconName: "ClipboardCheck" },
  { id: "study-material", label: "Study Material", href: "/student/study-material", iconName: "FileText" },
  { id: "boards", label: "Boards", href: "/student/boards", iconName: "Award" },
  { id: "notifications", label: "Notifications", href: "/student/notifications", iconName: "Bell" },
  { id: "profile", label: "Profile", href: "/student/profile", iconName: "User" },
];

export const HERO_SLIDES: HeroSlide[] = [
  {
    id: "hero-1",
    tagline: "TOPVEDA ACADEMIC DISCOVERY",
    title: "Learn. Practice. Grow.",
    subtitle: "Your future is built by what you do today.",
    ctaText: "Keep Learning →",
    ctaLink: "#featured-batches",
    quote: "Better Students\nBrighter Futures",
    characterImage: "/assets/student/hero-character.jpg",
  },
  {
    id: "hero-2",
    tagline: "TARGET BOARDS 2027",
    title: "Master Every Concept with Top Faculty.",
    subtitle: "Structured daily live sessions, comprehensive notes & mock tests.",
    ctaText: "Explore Batches →",
    ctaLink: "/student/batches",
    quote: "Excellence in Every Class",
    characterImage: "/assets/student/hero-character.jpg",
  },
];

export const FEATURED_BATCHES: FeaturedBatch[] = [
  {
    id: "fb-1",
    badge: { text: "New", variant: "orange" },
    board: "Class 10 CBSE",
    title: "Mathematics",
    subtitle: "Complete Board Preparation",
    educatorName: "Rohit Sir",
    educatorAvatar: "/assets/student/teacher-male-1.jpg",
    bgGradient: "from-sky-50/70 via-blue-50/40 to-indigo-50/30",
    borderColor: "border-sky-100",
    iconType: "math",
  },
  {
    id: "fb-2",
    badge: { text: "Popular", variant: "pink" },
    board: "Class 12 Science",
    title: "Physics + Chemistry",
    subtitle: "Full Syllabus Coverage",
    educatorName: "Neha Ma'am",
    educatorAvatar: "/assets/student/teacher-female-1.jpg",
    bgGradient: "from-pink-50/70 via-rose-50/40 to-orange-50/30",
    borderColor: "border-pink-100",
    iconType: "science",
  },
  {
    id: "fb-3",
    badge: { text: "New", variant: "green" },
    board: "JEE 2027",
    title: "Foundation Batch",
    subtitle: "Start Early, Stay Ahead",
    educatorName: "Arjun Sir",
    educatorAvatar: "/assets/student/teacher-male-1.jpg",
    bgGradient: "from-emerald-50/70 via-teal-50/40 to-green-50/30",
    borderColor: "border-emerald-100",
    iconType: "foundation",
  },
  {
    id: "fb-4",
    badge: { text: "New", variant: "purple" },
    board: "NEET 2027",
    title: "Complete Preparation",
    subtitle: "Learn from Expert Faculty",
    educatorName: "Dr. Priya Sharma",
    educatorAvatar: "/assets/student/teacher-doctor.jpg",
    bgGradient: "from-purple-50/70 via-violet-50/40 to-fuchsia-50/30",
    borderColor: "border-purple-100",
    iconType: "medical",
  },
];

export const ONGOING_BATCHES: OngoingBatch[] = [
  {
    id: "ob-1",
    badge: "Class 10 (CBSE)",
    batchName: "Mathematics",
    subject: "CBSE Board",
    status: "Live Now",
    statusType: "live",
    ctaText: "Join Now",
    iconBg: "bg-emerald-50 border-emerald-100 text-emerald-600",
    iconColor: "text-emerald-600",
    iconType: "target",
  },
  {
    id: "ob-2",
    badge: "Class 10 (Bihar Board)",
    batchName: "Science",
    subject: "BSEB Board",
    status: "Ongoing",
    statusType: "ongoing",
    ctaText: "View Details",
    iconBg: "bg-sky-50 border-sky-100 text-sky-600",
    iconColor: "text-sky-600",
    iconType: "atom",
  },
  {
    id: "ob-3",
    badge: "Class 12",
    batchName: "Commerce",
    subject: "Accounts & Eco",
    status: "Ongoing",
    statusType: "ongoing",
    ctaText: "View Details",
    iconBg: "bg-amber-50 border-amber-100 text-amber-600",
    iconColor: "text-amber-600",
    iconType: "book",
  },
  {
    id: "ob-4",
    badge: "JEE 2027",
    batchName: "Preparation",
    subject: "PCM Advanced",
    status: "Ongoing",
    statusType: "ongoing",
    ctaText: "View Details",
    iconBg: "bg-indigo-50 border-indigo-100 text-indigo-600",
    iconColor: "text-indigo-600",
    iconType: "academy",
  },
  {
    id: "ob-5",
    badge: "NEET 2027",
    batchName: "Preparation",
    subject: "PCB Medical",
    status: "Ongoing",
    statusType: "ongoing",
    ctaText: "View Details",
    iconBg: "bg-purple-50 border-purple-100 text-purple-600",
    iconColor: "text-purple-600",
    iconType: "medical",
  },
];

export const LIVE_CLASSES_TODAY: LiveClass[] = [
  {
    id: "lc-1",
    isLive: true,
    statusText: "LIVE",
    subject: "Mathematics",
    topic: "Trigonometry Basics",
    educatorName: "By Rohit Sir",
    educatorAvatar: "/assets/student/teacher-male-1.jpg",
    time: "6:00 PM",
    ctaText: "Join Class",
    ctaVariant: "primary",
  },
  {
    id: "lc-2",
    isLive: false,
    statusText: "UPCOMING",
    subject: "Science",
    topic: "Chemical Reactions",
    educatorName: "By Neha Ma'am",
    educatorAvatar: "/assets/student/teacher-female-1.jpg",
    time: "7:30 PM",
    ctaText: "Reminder",
    ctaVariant: "reminder",
  },
  {
    id: "lc-3",
    isLive: false,
    statusText: "UPCOMING",
    subject: "English",
    topic: "Writing Skills",
    educatorName: "By Arjun Sir",
    educatorAvatar: "/assets/student/teacher-male-1.jpg",
    time: "8:30 PM",
    ctaText: "Reminder",
    ctaVariant: "reminder",
  },
  {
    id: "lc-4",
    isLive: false,
    statusText: "UPCOMING",
    subject: "Physics",
    topic: "Laws of Motion",
    educatorName: "By Karan Sir",
    educatorAvatar: "/assets/student/teacher-male-1.jpg",
    time: "5:00 PM",
    ctaText: "Reminder",
    ctaVariant: "reminder",
  },
];

export const LATEST_LECTURES: Lecture[] = [
  {
    id: "lec-1",
    title: "Trigonometry Basics",
    subject: "Mathematics",
    teacherName: "By Rohit Sharma",
    duration: "45 min",
    durationFormatted: "45:00",
    thumbnailBg: "from-[#0F2042] via-[#162D59] to-[#0A162B]",
    categoryTag: "TRIGONOMETRY BASICS",
    educatorAvatar: "/assets/student/teacher-male-1.jpg",
  },
  {
    id: "lec-2",
    title: "Life Processes",
    subject: "Science",
    teacherName: "By Neha Ma'am",
    duration: "38 min",
    durationFormatted: "38:00",
    thumbnailBg: "from-[#0A362E] via-[#0E4A3F] to-[#062620]",
    categoryTag: "Life Processes",
    educatorAvatar: "/assets/student/teacher-female-1.jpg",
  },
  {
    id: "lec-3",
    title: "Grammar Rules",
    subject: "English",
    teacherName: "By Arjun Gupta",
    duration: "32 min",
    durationFormatted: "32:00",
    thumbnailBg: "from-[#2A1B4E] via-[#3B256E] to-[#1B1133]",
    categoryTag: "Grammar Rules",
    educatorAvatar: "/assets/student/teacher-female-1.jpg",
  },
  {
    id: "lec-4",
    title: "Chemical Reactions",
    subject: "Science",
    teacherName: "By Rohit Sharma",
    duration: "40 min",
    durationFormatted: "40:00",
    thumbnailBg: "from-[#0E344A] via-[#154E6E] to-[#092231]",
    categoryTag: "Chemical Reactions",
    educatorAvatar: "/assets/student/teacher-male-1.jpg",
  },
  {
    id: "lec-5",
    title: "Work, Energy & Power",
    subject: "Physics",
    teacherName: "By Karan Verma",
    duration: "36 min",
    durationFormatted: "36:00",
    thumbnailBg: "from-[#3D2314] via-[#59331D] to-[#26160C]",
    categoryTag: "Work, Energy & Power",
    educatorAvatar: "/assets/student/teacher-male-1.jpg",
  },
  {
    id: "lec-6",
    title: "Heredity and Evolution",
    subject: "Biology",
    teacherName: "By Dr. Priya Sharma",
    duration: "42 min",
    durationFormatted: "42:00",
    thumbnailBg: "from-[#0F382A] via-[#174F3B] to-[#0A261C]",
    categoryTag: "Heredity & Evolution",
    educatorAvatar: "/assets/student/teacher-doctor.jpg",
  },
];

export const EXPLORE_COURSES: CourseItem[] = [
  {
    id: "ec-1",
    title: "Class 10",
    category: "Mathematics",
    iconBg: "bg-rose-50 border-rose-100",
    iconColor: "text-rose-500",
    iconType: "school",
  },
  {
    id: "ec-2",
    title: "Class 10",
    category: "Science",
    iconBg: "bg-emerald-50 border-emerald-100",
    iconColor: "text-emerald-500",
    iconType: "flask",
  },
  {
    id: "ec-3",
    title: "Class 10",
    category: "English",
    iconBg: "bg-purple-50 border-purple-100",
    iconColor: "text-purple-500",
    iconType: "book",
  },
  {
    id: "ec-4",
    title: "Class 10",
    category: "PCM",
    iconBg: "bg-sky-50 border-sky-100",
    iconColor: "text-sky-500",
    iconType: "atom",
  },
  {
    id: "ec-5",
    title: "Class 12",
    category: "Science",
    iconBg: "bg-orange-50 border-orange-100",
    iconColor: "text-orange-500",
    iconType: "shield",
  },
  {
    id: "ec-6",
    title: "Class 12",
    category: "Commerce",
    iconBg: "bg-pink-50 border-pink-100",
    iconColor: "text-pink-500",
    iconType: "briefcase",
  },
  {
    id: "ec-7",
    title: "JEE",
    category: "Preparation",
    iconBg: "bg-amber-50 border-amber-100",
    iconColor: "text-amber-500",
    iconType: "test-tube",
  },
  {
    id: "ec-8",
    title: "NEET",
    category: "Preparation",
    iconBg: "bg-emerald-50 border-emerald-100",
    iconColor: "text-emerald-600",
    iconType: "stethoscope",
  },
];

export const WHATS_HAPPENING_ITEMS: HubItem[] = [
  {
    id: "hub-1",
    category: "announcement",
    badgeText: "NEW BATCH",
    badgeVariant: "orange",
    title: "Class 10 Mathematics Batch",
    description: "Enrollment is now officially open for the new 2026-27 Board Preparation batch.",
    ctaText: "Explore Batch",
    ctaLink: "/student/batches",
    iconType: "megaphone",
  },
  {
    id: "hub-2",
    category: "material",
    badgeText: "REVISION NOTES",
    badgeVariant: "sky",
    title: "New Science Formula Sheets",
    description: "Comprehensive quick-revision PDF notes and mindmaps are ready for download.",
    ctaText: "View Material",
    ctaLink: "/student/study-material",
    iconType: "book",
  },
  {
    id: "hub-3",
    category: "live",
    badgeText: "LIVE TODAY",
    badgeVariant: "purple",
    title: "Trigonometry Masterclass",
    description: "Join Rohit Sir live at 6:00 PM for deep concept drills and PYQ problem-solving.",
    ctaText: "View Class",
    ctaLink: "/student/live",
    iconType: "target",
  },
  {
    id: "hub-4",
    category: "tip",
    badgeText: "STUDY TIP",
    badgeVariant: "emerald",
    title: "Daily Practice Discipline",
    description: "Solving 5 previous-year questions every evening boosts board retention by 40%.",
    ctaText: "Read More",
    ctaLink: "/student/learning",
    iconType: "lightbulb",
  },
];

export const DAILY_MOTIVATION_QUOTE: DailyQuote = {
  quote: "Success is built by the small things you do consistently every day.",
  author: "TopVeda",
  active: true,
};

export const CHATBOT_CONFIG: ChatbotConfig = {
  enabled: true,
  name: "TopVeda AI",
  welcomeMessage: "TopVeda AI Assistant is coming soon!",
  placeholderText: "Your 24/7 personal academic tutor is currently undergoing training to assist you with doubt-solving, instant concept explanations, and personalized revision.",
};
